name: Pull request


on:
  push:
    branches: ['*']

jobs:
  yarn:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    - run: yarn install
    
    - run: yarn run validate


  npm:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    - run: npm install

    - run: npm run validate

 